development:
  secret_key_base: 8406e82e8a82410bea7db3d1ae4d32751dfb8fa61fed8607abd88d19237900bcafb68181b91331d3eeed64d33a8b5f46f1f10937c7d5763208769d52040eda34
  AWS_ACCESS_KEY_ID: AKIAI3FRZVKQDTR7ZOXQ
  AWS_SECRET_ACCESS_KEY: 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
  AWS_REGION: ap-south-1
  TWILIO_SID: AC8f2ab5d9ec4675dd80d298c38411fa2d
  TWILIO_AUTH_TOKEN: 2a848ca0814bf91ca9daf9436198e490
  TWILIO_PHONE_NUMBER: +17792132675
  CAPTCHA_SECRET_KEY: 6LcB14oUAAAAAIlui6X6yVFUwEl_pH3nZTXQGzO8
  CAPTCHA_SITE_KEY: 6LcB14oUAAAAAECYQgj3jfJeIWmPUlsmbToxNhfw

test:
  secret_key_base: f55ac591da19397b7d94f97181a112c98f5cdd3668c03fc2503312cf5a07f02f73f439364561b27b5cf6aa6c3992705425c342dba841d0e3fcb1168e47d753e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  AWS_ACCESS_KEY_ID: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  AWS_SECRET_ACCESS_KEY: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  AWS_REGION: <%= ENV["AWS_REGION"] %>
  TWILIO_SID: <%= ENV["TWILIO_SID"] %>
  TWILIO_AUTH_TOKEN: <%= ENV["TWILIO_AUTH_TOKEN"] %>
  TWILIO_PHONE_NUMBER: <%= ENV["TWILIO_PHONE_NUMBER"] %>
  CAPTCHA_SECRET_KEY: 6LcB14oUAAAAAIlui6X6yVFUwEl_pH3nZTXQGzO8
  CAPTCHA_SITE_KEY: 6LcB14oUAAAAAECYQgj3jfJeIWmPUlsmbToxNhfw